# Copyright 2019 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: krew
spec:
  version: "KREW_TAG"
  shortDescription: Package manager for kubectl plugins.
  caveats: |
    krew is now installed! To start using kubectl plugins, you need to add
    krew's installation directory to your PATH:

      * macOS/Linux:
        - Add the following to your ~/.bashrc or ~/.zshrc:
            export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"
        - Restart your shell.

      * Windows: Add %USERPROFILE%\.krew\bin to your PATH environment variable

    Run "kubectl krew" to list krew commands and get help.
    You can find documentation at https://github.com/kubernetes-sigs/krew.

  platforms:
  - uri: https://github.com/kubernetes-sigs/krew/releases/download/KREW_TAG/krew.tar.gz
    sha256: KREW_TAR_CHECKSUM
    bin: krew
    files:
    - from: ./krew-darwin_amd64
      to: krew
    selector:
      matchLabels:
        os: darwin
        arch: amd64
  - uri: https://github.com/kubernetes-sigs/krew/releases/download/KREW_TAG/krew.tar.gz
    sha256: KREW_TAR_CHECKSUM
    bin: krew
    files:
    - from: ./krew-linux_amd64
      to: krew
    selector:
      matchLabels:
        os: linux
        arch: amd64
  - uri: https://github.com/kubernetes-sigs/krew/releases/download/KREW_TAG/krew.tar.gz
    sha256: KREW_TAR_CHECKSUM
    bin: krew
    files:
    - from: ./krew-linux_arm
      to: krew
    selector:
      matchLabels:
        os: linux
        arch: arm
  - uri: https://github.com/kubernetes-sigs/krew/releases/download/KREW_TAG/krew.zip
    sha256: KREW_ZIP_CHECKSUM
    bin: krew.exe
    files:
    - from: ./krew-windows_amd64.exe
      to: krew.exe
    selector:
      matchLabels:
        os: windows
        arch: amd64
